workflows:
  react-native-ios:
    name: React Native iOS - NM DigitalHub
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: NMDigitalHUB
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: nm-digitalhub.com
      groups:
        - codemagic
      vars:
        BUNDLE_ID: "nm-digitalhub.com"
        XCODE_WORKSPACE: "NMDigitalHub.xcworkspace"
        XCODE_SCHEME: "NMDigitalHub"
        APP_NAME: "NM-DigitalHUB"
        APP_STORE_APPLE_ID: 6747678252
      node: 18.17.0
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
        - pattern: master
          include: true
    cache:
      cache_paths:
        - $HOME/.npm
        - ios/Pods
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - netanel.kalfa@kalfa.me
          - admin@nm-digitalhub.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        beta_groups:
          - Internal Testing
        # submit_to_app_store: false

  # Optional: Build for testing without App Store upload
  react-native-ios-testing:
    name: React Native iOS - Testing Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: nm-digitalhub.com
      groups:
        - codemagic
      vars:
        BUNDLE_ID: "nm-digitalhub.com"
        XCODE_WORKSPACE: "NMDigitalHub.xcworkspace"
        XCODE_SCHEME: "NMDigitalHub"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    cache:
      cache_paths:
        - $HOME/.npm
        - ios/Pods
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files for ad-hoc
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_ADHOC --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build ipa for testing
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - netanel.kalfa@kalfa.me
          - admin@nm-digitalhub.com
        notify:
          success: true
          failure: true